name: appwrite_function_context
description: A wrapper around the Appwrite Function Context.
version: 1.0.0
homepage: https://github.com/Colton127/appwrite_function_context

environment:
  sdk: ^3.5.0

dependencies:

dev_dependencies:
