name: appwrite_function_context
description: A wrapper around the Appwrite Function Context.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:

dev_dependencies:
